-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb({{colors.primary.default.hex_stripped}})",
			inactive_border = "rgb({{colors.outline.default.hex_stripped}})",
		},
	},
	group = {
		col = {
			border_active = "rgb({{colors.primary.default.hex_stripped}})",
			border_inactive = "rgb({{colors.outline.default.hex_stripped}})",
			border_locked_active = "rgb({{colors.error.default.hex_stripped}})",
			border_locked_inactive = "rgb({{colors.outline.default.hex_stripped}})",
		},
		groupbar = {
			col = {
				active = "rgb({{colors.primary.default.hex_stripped}})",
				inactive = "rgb({{colors.outline.default.hex_stripped}})",
				locked_active = "rgb({{colors.error.default.hex_stripped}})",
				locked_inactive = "rgb({{colors.outline.default.hex_stripped}})",
			},
		},
	},
})

-- Effect colors exist only on newer Hyprland; skip them elsewhere instead of raising config errors
local function themed(key, value)
	local ok, current = pcall(hl.get_config, key)
	if ok and current ~= nil then
		hl.config({ [key] = value })
	end
end

themed("decoration.glow.color", "rgba({{colors.primary.default.hex_stripped}}ee)")
themed("decoration.glow.color_inactive", "rgba({{colors.outline.default.hex_stripped}}ee)")
themed("decoration.blur.acrylic.tint", "rgba({{colors.primary.default.hex_stripped}}14)")
themed("decoration.blur.aurora.color1", "rgba({{colors.primary.default.hex_stripped}}29)")
themed("decoration.blur.aurora.color2", "rgba({{colors.tertiary.default.hex_stripped}}7a)")
themed("decoration.blur.fluid_jar.color", "rgba({{colors.primary.default.hex_stripped}}cc)")
