package providers

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/AvengeMedia/DankMaterialShell/core/internal/keybinds"
)

func TestHyprlandProviderGetCheatSheet(t *testing.T) {
	tmpDir := t.TempDir()
	configFile := filepath.Join(tmpDir, "hyprland.lua")

	content := `hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"), { description = "Terminal" })
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
`

	if err := os.WriteFile(configFile, []byte(content), 0o644); err != nil {
		t.Fatalf("Failed to write test config: %v", err)
	}

	p := NewHyprlandProvider(tmpDir)
	sheet, err := p.GetCheatSheet()

	if err != nil {
		t.Fatalf("GetCheatSheet failed: %v", err)
	}

	if len(sheet.Binds) == 0 {
		t.Error("expected categorized bindings, got none")
	}

	if windowBinds, ok := sheet.Binds["Window"]; !ok || len(windowBinds) == 0 {
		t.Error("expected Window category with bindings")
	}

	if execBinds, ok := sheet.Binds["Execute"]; !ok || len(execBinds) == 0 {
		t.Error("expected Execute category with bindings")
	}

	if wsBinds, ok := sheet.Binds["Workspace"]; !ok || len(wsBinds) == 0 {
		t.Error("expected Workspace category with bindings")
	}
}

func TestFormatKey(t *testing.T) {
	tmpDir := t.TempDir()
	configFile := filepath.Join(tmpDir, "hyprland.lua")

	tests := []struct {
		name     string
		content  string
		expected string
		category string
	}{
		{
			name:     "multiple mods",
			content:  `hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))`,
			expected: "SUPER+SHIFT+F",
			category: "Window",
		},
		{
			name:     "no mods",
			content:  `hl.bind("Print", hl.dsp.exec_cmd("screenshot"))`,
			expected: "Print",
			category: "Execute",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := os.WriteFile(configFile, []byte(tt.content), 0o644); err != nil {
				t.Fatalf("Failed to write test config: %v", err)
			}

			p := NewHyprlandProvider(tmpDir)
			sheet, err := p.GetCheatSheet()
			if err != nil {
				t.Fatalf("GetCheatSheet failed: %v", err)
			}

			categoryBinds, ok := sheet.Binds[tt.category]
			if !ok || len(categoryBinds) == 0 {
				t.Fatalf("expected binds in category %q", tt.category)
			}

			if categoryBinds[0].Key != tt.expected {
				t.Errorf("Key = %q, want %q", categoryBinds[0].Key, tt.expected)
			}
		})
	}
}

func TestDescriptionFallback(t *testing.T) {
	tmpDir := t.TempDir()
	configFile := filepath.Join(tmpDir, "hyprland.lua")

	tests := []struct {
		name     string
		content  string
		wantDesc string
	}{
		{
			name:     "autogenerated description for known dispatcher",
			content:  `hl.bind("SUPER + Q", hl.dsp.window.close())`,
			wantDesc: "Close window",
		},
		{
			name:     "custom comment overrides autogeneration",
			content:  `hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"), { description = "Open terminal" })`,
			wantDesc: "Open terminal",
		},
		{
			name:     "trailing comment overrides autogeneration",
			content:  `hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty")) -- Open terminal`,
			wantDesc: "Open terminal",
		},
		{
			name:     "fallback for unknown Lua expression",
			content:  `hl.bind("SUPER + W", hl.dsp.no_op())`,
			wantDesc: "hl.dsp.no_op()",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := os.WriteFile(configFile, []byte(tt.content), 0o644); err != nil {
				t.Fatalf("Failed to write test config: %v", err)
			}

			p := NewHyprlandProvider(tmpDir)
			sheet, err := p.GetCheatSheet()
			if err != nil {
				t.Fatalf("GetCheatSheet failed: %v", err)
			}

			found := false
			for _, binds := range sheet.Binds {
				for _, bind := range binds {
					if bind.Description == tt.wantDesc {
						found = true
						break
					}
				}
				if found {
					break
				}
			}

			if !found {
				t.Errorf("expected description %q not found in any bind", tt.wantDesc)
			}
		})
	}
}

func TestHyprlandModKeyFromLuaMainMod(t *testing.T) {
	tmpDir := t.TempDir()
	content := `local mainMod = "ALT"
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("kitty"))
`
	if err := os.WriteFile(filepath.Join(tmpDir, "hyprland.lua"), []byte(content), 0o644); err != nil {
		t.Fatalf("Failed to write test config: %v", err)
	}

	sheet, err := NewHyprlandProvider(tmpDir).GetCheatSheet()
	if err != nil {
		t.Fatalf("GetCheatSheet failed: %v", err)
	}
	want := keybinds.ModKey{Resolved: "Alt", Source: keybinds.ModSourceConfig}
	if sheet.Mod != want {
		t.Errorf("Mod = %+v, want %+v", sheet.Mod, want)
	}
}

func TestHyprlandConvertKeybindLuaAction(t *testing.T) {
	tests := []struct {
		dispatcher, params string
		want               string
	}{
		{"movefocus", "l", `hl.dsp.focus({ direction = "l" })`},
		{"workspaceopt", "allfloat", ""},
		{"hl.dsp.no_op()", "", ""},
	}
	p := NewHyprlandProvider(t.TempDir())
	p.luaConfig = true
	for _, tt := range tests {
		t.Run(tt.dispatcher+" "+tt.params, func(t *testing.T) {
			kb := &HyprlandKeyBinding{Mods: []string{"SUPER"}, Key: "X", Dispatcher: tt.dispatcher, Params: tt.params}
			if got := p.convertKeybind(kb, "", nil, nil).LuaAction; got != tt.want {
				t.Fatalf("LuaAction = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestHyprlandLuaBindLabels(t *testing.T) {
	tests := []struct {
		expr string
		want string
	}{
		{`hl.dsp.window.move({ monitor = "l" })`, "move to left monitor"},
		{`hl.dsp.focus({ window = "first" })`, "focus window first"},
		{`hl.dsp.window.resize({ x = -100, y = 0, relative = true })`, "Shrink window width by 100"},
		{`hl.dsp.window.move({ workspace = "special:magic", follow = false })`, "move to special workspace magic"},
		{`hl.dsp.window.move({ into_group = "r" })`, "move into right group"},
	}
	for _, tt := range tests {
		t.Run(tt.expr, func(t *testing.T) {
			if got := luaKeyComboToBinding("SUPER + X", tt.expr, "", "").Comment; got != tt.want {
				t.Fatalf("Comment = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestHyprlandCheatSheetConfigFormat(t *testing.T) {
	const conf = "bind = SUPER, Q, killactive\n"
	const lua = `hl.bind("SUPER + Q", hl.dsp.window.close())` + "\n"
	tests := []struct {
		name         string
		files        map[string]string
		wantFormat   string
		wantReadOnly bool
		wantLua      string
	}{
		{"hyprlang only", map[string]string{"hyprland.conf": conf}, "hyprlang", true, ""},
		{"lua only", map[string]string{"hyprland.lua": lua}, "lua", false, `hl.dsp.window.close()`},
		{"lua wins over leftover conf", map[string]string{"hyprland.conf": conf, "hyprland.lua": lua}, "lua", false, `hl.dsp.window.close()`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			if err := os.MkdirAll(filepath.Join(dir, "dms"), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(dir, "dms", "binds.lua"), nil, 0o644); err != nil {
				t.Fatal(err)
			}
			for name, content := range tt.files {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			sheet, err := NewHyprlandProvider(dir).GetCheatSheet()
			if err != nil {
				t.Fatalf("GetCheatSheet: %v", err)
			}
			if sheet.DMSStatus == nil || sheet.DMSStatus.ConfigFormat != tt.wantFormat || sheet.DMSStatus.ReadOnly != tt.wantReadOnly {
				t.Fatalf("DMSStatus = %+v, want format %q readOnly %v", sheet.DMSStatus, tt.wantFormat, tt.wantReadOnly)
			}
			binds := sheet.Binds["Window"]
			if len(binds) != 1 || binds[0].Action != "killactive" || binds[0].LuaAction != tt.wantLua {
				t.Fatalf("Window binds = %+v, want killactive with LuaAction %q", binds, tt.wantLua)
			}
		})
	}
}
